apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forms.readlayout" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: readlayout
data:
  eula: accept
---