apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forms.customsupervised" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: customsupervised
type: Opaque
data:
  customSupervisedApiKey: {{ .Values.customSupervised.apiKey | b64enc }}
  customSupervisedEndpointUri: {{ .Values.customSupervised.endpointUri | b64enc }}  