apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forms.readlayout" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: readlayout
type: Opaque
data:
  readLayoutApiKey: {{ .Values.readLayout.apiKey | b64enc }}
  readLayoutEndpointUri: {{ .Values.readLayout.endpointUri | b64enc }}    