apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forms.storage" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: storage
type: Opaque
data:
  azurestorageaccountkey: {{ .Values.storage.key | b64enc }}
  azurestorageaccountname: {{ .Values.storage.name | b64enc }}