apiVersion: v1
kind: Service
metadata:
  name: {{ template "forms.customsupervised" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: customsupervised
spec:
  type: {{ .Values.customSupervised.service.type }}
  ports: 
    - port: {{ .Values.customSupervised.service.port }}
      targetPort: cs-http
      name: {{ template "forms.customsupervised" . }}
    - port: {{ .Values.readLayout.service.port }}
      targetPort: rl-http
      name: {{ template "forms.readlayout" . }}            
  selector:
    app: {{ template "forms.name" . }}
    release: {{ .Release.Name }}
    component: customsupervised