apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forms.formsrecognizer" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: formsrecognizer
data:
  eula: accept
---