apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forms.computervision" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: computervision
type: Opaque
data:
  computerVisionApiKey: {{ .Values.computerVision.apiKey | b64enc }}
  computerVisionEndpointUri: {{ .Values.computerVision.endpointUri | b64enc }}