apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forms.formsrecognizer" . }}
  labels:
    app: {{ template "forms.name" . }}
    chart: {{ template "forms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: formsrecognizer
type: Opaque
data:
  formsRecognizerApiKey: {{ .Values.formsRecognizer.apiKey | b64enc }}
  formsRecognizerEndpointUri: {{ .Values.formsRecognizer.endpointUri | b64enc }}